#profile https://stackoverflow.com/questions/28007686/how-can-i-provide-different-database-configurations-with-spring-boot

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_dev_user
    password: guru
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true